[build-system]
requires = ["setuptools>=68", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "ramybuilder"
version = "0.1.0"
description = "Professional Ren'Py Walkthrough Builder"
authors = [
    {name="Ramy"}
]
requires-python = ">=3.11"

dependencies = []

[tool.setuptools]
package-dir = {"" = "src"}

[tool.setuptools.packages.find]
where = ["src"]
